### ISSUE TITLE
Hierarchical view of muscle groups and the muscles belonging to each group

### ISSUE THREAD

**Issue by seesharper** [bpjohannessen/muscledb-web#57]
*MuscleGroup1* 

- Muscle1
- Muscle2
- *MuscleSubGroup1*
  - Muscle3
  - Muslce4

**Comment by bpjohannessen** [comment]
*MuscleGroup1* 

- Muscle1
- Muscle2

*MuscleGroup2*
  - Muscle3
  - Muscle4

*MuscleGroup3*
 - MuscleSubGroup1
    - Muscle5
    - Muscle6
  - MuscleSubGroup2
    - Muscle7
    - Muscle8

No groups or subgroups have muscles AND a subgroup/subsubgroup. They have either muscles and no subgroup, or a subgroup with muscles.
