### ISSUE TITLE
Search results stack upon each other

### ISSUE THREAD

**Issue by bpjohannessen** [bpjohannessen/muscledb-web#8]
If I search for "gluteus", remove the text and search for "triceps" the search results will stack on each other. Some kind of "remove" (opposite of "append") is missing, probably.

**Comment by seesharper** [comment]
This should do the trick
https://api.jquery.com/empty/

**Comment by bpjohannessen** [comment]
![skjermbilde 2017-01-29 kl 13 30 00](https://cloud.githubusercontent.com/assets/6560822/22403994/20257b76-e627-11e6-82c1-5902c260e1a1.png)

**Comment by bpjohannessen** [comment]
Closed. I have not been able to reproduce this issue.
